### ISSUE TITLE
MySQL Support

### ISSUE THREAD

**Issue by Mecanik** [tchoulom/ViewCounterBundle#10]
First of all, amazing work! Is there any chance you can add (or explain how to add) MySQL support for storage of views + statistics?

Thank you.

**Comment by tchoulom** [comment]
MySQL support for storage of views + statistics is not yet available.
The storage currently uses "filesystem" and "mongodb" engines.

You can also add a custom storage service by implementing the "Tchoulom\ViewCounterBundle\Adapter\Storage\StorageAdapterInterface"  interface as explained in the documentation (in the "storage" paragraph) : 
 https://github.com/tchoulom/ViewCounterBundle/blob/master/Resources/doc/readme/usage-step-1-5.md#usage 

Thanks !
