### ISSUE TITLE
Deprecation warning

### ISSUE THREAD

**Issue by melroy89** [tchoulom/ViewCounterBundle#12]
Cold you help to resolve this warning:

`User Deprecated: The "App\Entity\ViewCounter::setPage()" method will require a new "string $property" argument in the next major version of its parent class "Tchoulom\ViewCounterBundle\Entity\ViewCounter", not defining it is deprecated.`

My method now looks like this:

```php
    public function setPage(ViewCountable $page): ViewCounter
    {
        $this->entry = $page;

        return $this;
    }
```

The warning is not clear about the location of the new argument or if it will replace any existing argument.  Or even what to do with the $property value.!?

**Comment by tchoulom** [comment]
What version of "ViewCounterBundle" are you using?

**Comment by melroy89** [comment]
v6.1.0 (https://github.com/MbinOrg/mbin/blob/main/composer.lock), sorry  I didn't mentioned the project indeed: https://github.com/MbinOrg/mbin

**Comment by tchoulom** [comment]
Why are you implementing the "setPage" and "getPage" functions? These functions are already implemented in the bundle https://github.com/tchoulom/ViewCounterBundle/blob/master/Entity/ViewCounter.php:

```
public function setPage(ViewCountable $page): self
{
     $property = $this->getProperty();
     $setPage = 'set' . ucfirst($property);
     $this->$setPage($page);

     return $this;
 }

```
Be careful, this function depends on the variable "$property" ($property = $this->getProperty();) which you seem not to take into account in your entity:

```
public function setPage(ViewCountable $page): ViewCounter
{
     $this->entry = $page;

     return $this;
}
```

**Comment by melroy89** [comment]
> Why are you implementing the "setPage" and "getPage" functions?

Uh.. let's call it legacy reasons... 😖 

I'm glad to fix up the code and remove those methods if there is no need to implement them in the first place! So let's see what happens if I just remove the methods completely in this child class.
