### ISSUE TITLE
Error message in profiler

### ISSUE THREAD

**Issue by jchesne** [tchoulom/ViewCounterBundle#2]
Hi,
I have this error on profiler:
`The field mybundle\Entity\myentity#viewCounters is on the inverse side of a bi-directional relationship, but the specified mappedBy association on the target-entity mybundle\Entity\ViewCounter#event does not contain the required 'inversedBy="viewCounters"' attribute.`
Do i missed something ?

**Comment by tchoulom** [comment]
Hi,

You must add inversedBy="viewCounters" in the ViewCounter class:

        /**
         * @ORM\ManyToOne(targetEntity="Article", cascade={"persist"}, inversedBy="viewCounters")
         * @ORM\JoinColumn(nullable=true)
         */
        private $article;

The documentation has been updated accordingly.

Thanks.
