### ISSUE TITLE
Trouble to make FileStatFinder working with MongoDB

### ISSUE THREAD

**Issue by apsylone** [tchoulom/ViewCounterBundle#22]
Hi,

I'm trying to make my FileStatFinder working with MongoDB.
Everything is working fine (documents are in DB, views are incremented...), but when using the FileStatFinder, I get an empty array.
Do I am using it in the wrong way ? I suspect that the FileStatFinder class is only for file stats, but what is there a MongoDB implementation so ? :-) 

Thanks for your help @tchoulom and for your bundle,

**Comment by tchoulom** [comment]
Hi,

The "FileStatsFinder" service, as its name suggests, is intended to perform statistical searches in a statistics file. Currently, it is not yet configured to perform searches in a MongoDB database, but you have the possibility to implement it according to the needs of your project.

**Comment by apsylone** [comment]
Hi @tchoulom , 

Thanks for your message. Could you help me implementing this ? Do you have some example to share ?
I have a MariaDB and a MongoDB (for statistical data). The data is inserted in the MongoDB via saveView() but I cannot get it as each time I have an empty array (i've tried with documentManager).

Thanks for your help,

**Comment by tchoulom** [comment]
Hi,
I suggest you take as an example the file statistics data management implemented in the "FileStatsFinder" service:  https://github.com/tchoulom/ViewCounterBundle/blob/master/Finder/FileStatsFinder.php. 
You can use this approach as a reference to adapt the implementation according to your specific needs, whether for a MariaDB or MongoDB database.
