### ISSUE TITLE
Does not work with symfony 5

### ISSUE THREAD

**Issue by ngrdanjski** [tchoulom/ViewCounterBundle#3]
I'm trying to install this cool bundle on symfony 5, but throws a error.

 - tchoulom/view-counter-bundle 3.7.3 requires symfony/framework-bundle ^2.7 || ^3.0 || ^4.0 -> no matching package found.
    - tchoulom/view-counter-bundle 3.7.2 requires symfony/framework-bundle ^2.7 || ^3.0 || ^4.0 -> no matching package found.
    - tchoulom/view-counter-bundle 3.7.1 requires symfony/framework-bundle ^2.7 || ^3.0 || ^4.0 -> no matching package found.
    - tchoulom/view-counter-bundle 3.7.0 requires symfony/framework-bundle ^2.7 || ^3.0 || ^4.0 -> no matching package found.
    - Installation request for tchoulom/view-counter-bundle ^3.7 -> satisfiable by tchoulom/view-counter-bundle[3.7.0, 3.7.1, 3.7.2, 3.7.3].

**Comment by tchoulom** [comment]
Hi,
The Viewcounter bundle is now upgraded to Symfony 5.
Thanks!
