### ISSUE TITLE
Error during composer installation during cache:clear

### ISSUE THREAD

**Issue by 0xbeefed** [tchoulom/ViewCounterBundle#8]
When running `composer require tchoulom/view-counter-bundle`, I get this kind of blurry message that makes the install fail.

Composer version: Composer version 2.0.6 2020-11-07 11:21:17
Symfony version: 
- Symfony CLI version v4.21.3 (2020-12-11T09:19:56+0000 - stable)
- Symfony 5.2.1 (env: dev, debug: true)

![image](https://user-images.githubusercontent.com/20847882/103084595-ab5db200-45df-11eb-81d9-a5950a34a7e2.png)

**Comment by tchoulom** [comment]
The error is explicit.

You must configure the bundle correctly: 
https://github.com/tchoulom/ViewCounterBundle/blob/master/Resources/doc/readme/usage-step-1-5.md#step-3-configuration

**The complete configuration**: 
https://github.com/tchoulom/ViewCounterBundle/blob/master/Resources/doc/readme/usage-step-1-5.md#step-1-interface-and-property
