### ISSUE TITLE
Storage

### ISSUE THREAD

**Issue by query929** [tchoulom/ViewCounterBundle#9]
I want to use **filesystem** storage, but get an error
![Screenshot_2](https://user-images.githubusercontent.com/77330499/114057571-577b8e00-989b-11eb-955d-468458998de3.png)

**tchoulom_viewcounter.yaml**
![Screenshot_3](https://user-images.githubusercontent.com/77330499/114058022-c6f17d80-989b-11eb-893f-c16282a120f5.png)

**composer.json**
![Screenshot_2](https://user-images.githubusercontent.com/77330499/114058202-ed171d80-989b-11eb-9fda-4838fcdf3d7b.png)

**Comment by tchoulom** [comment]
The error is fixed.
Thanks!
